### ISSUE TITLE
AX-13 Dummy endpoints for future classify methods

### ISSUE THREAD

**Issue by PostMetalFun1992** [PostMetalFun1992/ABC-XYZ#19]
### TODO:
- [x] Endpoints (POST) for ABC and XYZ methods
- [x] Validation based on nomenclature list
- [x] Issue human-read data for test json's
